baseURL = "https://qygame.github.io"
title = "QYGame"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = false
style = 'manni'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'