baseURL = "https://qygame.github.io/blog"
title = "QYGame"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
style = 'manni'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book@v12.0.0'